import {
  int,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
  json,
  boolean,
  decimal,
  index,
} from "drizzle-orm/mysql-core";

/**
 * Advisory Reports - AI-generated compliance and standards advisory documents
 * 
 * Stores comprehensive advisory reports generated by ISA's LLM integration.
 * Supports versioning and Lane C governance constraints (Decision 4: deferred to Phase 9).
 */
export const advisoryReports = mysqlTable(
  "advisory_reports",
  {
    id: int("id").autoincrement().primaryKey(),
    title: varchar("title", { length: 512 }).notNull(),
    reportType: mysqlEnum("reportType", [
      "COMPLIANCE_ASSESSMENT",
      "STANDARDS_MAPPING",
      "REGULATION_IMPACT",
      "IMPLEMENTATION_GUIDE",
      "GAP_ANALYSIS",
      "SECTOR_ADVISORY",
      "CUSTOM",
    ]).notNull(),
    
    // Content
    executiveSummary: text("executiveSummary"),
    content: text("content").notNull(), // Full report content (markdown)
    findings: json("findings").$type<Array<{
      category: string;
      severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
      description: string;
      recommendation: string;
    }>>(),
    recommendations: json("recommendations").$type<string[]>(),
    
    // Scope & Context
    targetRegulationIds: json("targetRegulationIds").$type<number[]>(),
    targetStandardIds: json("targetStandardIds").$type<number[]>(),
    sectorTags: json("sectorTags").$type<string[]>(),
    gs1ImpactTags: json("gs1ImpactTags").$type<string[]>(),
    
    // Generation Metadata
    version: varchar("version", { length: 32 }).notNull(), // e.g., "1.0", "1.1"
    generatedDate: timestamp("generatedDate").defaultNow().notNull(),
    generatedBy: varchar("generatedBy", { length: 255 }), // User or "AI_SYSTEM"
    llmModel: varchar("llmModel", { length: 128 }), // Which LLM model was used
    generationPrompt: text("generationPrompt"), // Prompt used for generation
    
    // Quality & Validation
    qualityScore: decimal("qualityScore", { precision: 3, scale: 2 }), // 0.00-1.00
    reviewStatus: mysqlEnum("reviewStatus", [
      "DRAFT",
      "UNDER_REVIEW",
      "APPROVED",
      "PUBLISHED",
      "ARCHIVED",
    ]).default("DRAFT").notNull(),
    reviewedBy: varchar("reviewedBy", { length: 255 }),
    reviewedAt: timestamp("reviewedAt"),
    reviewNotes: text("reviewNotes"),
    
    // Lane C Governance (Decision 4: publication deferred)
    publicationStatus: mysqlEnum("publicationStatus", [
      "INTERNAL_ONLY",
      "READY_FOR_PUBLICATION",
      "PUBLISHED",
      "WITHDRAWN",
    ]).default("INTERNAL_ONLY").notNull(),
    laneStatus: mysqlEnum("laneStatus", ["LANE_A", "LANE_B", "LANE_C"])
      .default("LANE_C")
      .notNull(),
    governanceNotes: text("governanceNotes"),
    
    // Usage Tracking
    viewCount: int("viewCount").default(0),
    downloadCount: int("downloadCount").default(0),
    lastAccessedAt: timestamp("lastAccessedAt"),
    
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  table => ({
    reportTypeIdx: index("reportType_idx").on(table.reportType),
    reviewStatusIdx: index("reviewStatus_idx").on(table.reviewStatus),
    publicationStatusIdx: index("publicationStatus_idx").on(table.publicationStatus),
    generatedDateIdx: index("generatedDate_idx").on(table.generatedDate),
  })
);

export type AdvisoryReport = typeof advisoryReports.$inferSelect;
export type InsertAdvisoryReport = typeof advisoryReports.$inferInsert;

/**
 * Advisory Report Versions - Track version history of advisory reports
 */
export const advisoryReportVersions = mysqlTable(
  "advisory_report_versions",
  {
    id: int("id").autoincrement().primaryKey(),
    reportId: int("reportId").notNull(), // Reference to advisoryReports.id
    version: varchar("version", { length: 32 }).notNull(),
    content: text("content").notNull(),
    changeLog: text("changeLog"), // What changed in this version
    createdBy: varchar("createdBy", { length: 255 }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  table => ({
    reportIdIdx: index("reportId_idx").on(table.reportId),
  })
);

export type AdvisoryReportVersion = typeof advisoryReportVersions.$inferSelect;
export type InsertAdvisoryReportVersion = typeof advisoryReportVersions.$inferInsert;
