/**
 * Privacy Policy Page
 * 
 * GDPR-compliant privacy policy for ISA (Intelligent Standards Architect).
 */

import { Card } from "@/components/ui/card";

export default function PrivacyPolicy() {
  return (
    <div className="container py-8 max-w-4xl">
      <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
      <p className="text-muted-foreground mb-8">
        Last updated: January 2, 2026
      </p>

      <Card className="p-8 space-y-8">
        <section>
          <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
          <p className="text-foreground leading-relaxed">
            Welcome to the Intelligent Standards Architect (ISA), operated by GS1 Netherlands. 
            We are committed to protecting your personal data and respecting your privacy. This 
            privacy policy explains how we collect, use, and safeguard your information when you 
            use our platform.
          </p>
          <p className="text-foreground leading-relaxed mt-4">
            ISA is designed to help organizations navigate ESG regulations and GS1 standards. 
            We process minimal personal data necessary to provide our services and comply with 
            applicable data protection laws, including the General Data Protection Regulation (GDPR).
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">2. Data Controller</h2>
          <p className="text-foreground leading-relaxed">
            The data controller responsible for your personal data is:
          </p>
          <div className="bg-muted p-4 rounded-lg mt-4">
            <p className="font-medium">GS1 Netherlands</p>
            <p className="text-muted-foreground">Stationsplein 9K</p>
            <p className="text-muted-foreground">3818 LE Amersfoort</p>
            <p className="text-muted-foreground">The Netherlands</p>
            <p className="text-muted-foreground mt-2">Email: info@gs1.nl</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">3. Information We Collect</h2>
          <p className="text-foreground leading-relaxed mb-4">
            We collect and process the following types of information:
          </p>

          <h3 className="text-xl font-medium mb-3">3.1 Account Information</h3>
          <p className="text-foreground leading-relaxed mb-4">
            When you create an account or log in via Manus OAuth, we collect:
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground ml-4">
            <li>Name and email address</li>
            <li>User ID (generated by our authentication system)</li>
            <li>Account creation date</li>
            <li>Role (user or admin)</li>
          </ul>

          <h3 className="text-xl font-medium mb-3 mt-6">3.2 Usage Data</h3>
          <p className="text-foreground leading-relaxed mb-4">
            We automatically collect information about how you use ISA:
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground ml-4">
            <li>Pages viewed and features accessed</li>
            <li>Search queries and filters applied</li>
            <li>Analysis requests and AI interactions</li>
            <li>Time spent on the platform</li>
            <li>Device type and browser information</li>
          </ul>

          <h3 className="text-xl font-medium mb-3 mt-6">3.3 User-Generated Content</h3>
          <p className="text-foreground leading-relaxed mb-4">
            When you use ISA's features, we store:
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground ml-4">
            <li>Saved regulations and standards</li>
            <li>Custom alerts and notifications</li>
            <li>Analysis history and reports</li>
            <li>Collaboration notes and comments</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">4. How We Use Your Information</h2>
          <p className="text-foreground leading-relaxed mb-4">
            We use your personal data for the following purposes:
          </p>

          <div className="space-y-4">
            <div>
              <h3 className="text-lg font-medium mb-2">4.1 Service Provision</h3>
              <p className="text-foreground leading-relaxed">
                To provide and maintain ISA's core functionality, including regulation tracking, 
                standards mapping, AI-powered analysis, and personalized recommendations.
              </p>
              <p className="text-muted-foreground text-sm mt-2">
                <strong>Legal basis:</strong> Performance of contract (GDPR Article 6(1)(b))
              </p>
            </div>

            <div>
              <h3 className="text-lg font-medium mb-2">4.2 Communication</h3>
              <p className="text-foreground leading-relaxed">
                To send you important updates about regulations, system notifications, and 
                responses to your inquiries.
              </p>
              <p className="text-muted-foreground text-sm mt-2">
                <strong>Legal basis:</strong> Legitimate interests (GDPR Article 6(1)(f))
              </p>
            </div>

            <div>
              <h3 className="text-lg font-medium mb-2">4.3 Improvement and Analytics</h3>
              <p className="text-foreground leading-relaxed">
                To analyze usage patterns, improve our services, and develop new features based 
                on aggregated, anonymized data.
              </p>
              <p className="text-muted-foreground text-sm mt-2">
                <strong>Legal basis:</strong> Legitimate interests (GDPR Article 6(1)(f))
              </p>
            </div>

            <div>
              <h3 className="text-lg font-medium mb-2">4.4 Security and Compliance</h3>
              <p className="text-foreground leading-relaxed">
                To protect against fraud, ensure platform security, and comply with legal 
                obligations.
              </p>
              <p className="text-muted-foreground text-sm mt-2">
                <strong>Legal basis:</strong> Legal obligation (GDPR Article 6(1)(c)) and 
                legitimate interests (GDPR Article 6(1)(f))
              </p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">5. Data Sharing and Disclosure</h2>
          <p className="text-foreground leading-relaxed mb-4">
            We do not sell your personal data. We may share your information only in the 
            following circumstances:
          </p>

          <h3 className="text-xl font-medium mb-3">5.1 Service Providers</h3>
          <p className="text-foreground leading-relaxed mb-4">
            We work with trusted third-party service providers who assist in operating ISA:
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground ml-4">
            <li><strong>Hosting:</strong> Manus (cloud infrastructure and deployment)</li>
            <li><strong>Database:</strong> TiDB Serverless (data storage)</li>
            <li><strong>Authentication:</strong> Manus OAuth (user authentication)</li>
            <li><strong>AI Services:</strong> OpenAI (content analysis and recommendations)</li>
          </ul>
          <p className="text-foreground leading-relaxed mt-4">
            All service providers are contractually bound to protect your data and use it only 
            for the purposes we specify.
          </p>

          <h3 className="text-xl font-medium mb-3 mt-6">5.2 Legal Requirements</h3>
          <p className="text-foreground leading-relaxed">
            We may disclose your information if required by law, court order, or governmental 
            authority, or to protect our rights, property, or safety.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">6. Data Retention</h2>
          <p className="text-foreground leading-relaxed mb-4">
            We retain your personal data only as long as necessary for the purposes outlined 
            in this policy:
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground ml-4">
            <li><strong>Account data:</strong> Retained while your account is active and for 
              90 days after account deletion</li>
            <li><strong>Usage logs:</strong> Retained for 12 months for security and analytics</li>
            <li><strong>Analysis history:</strong> Retained while your account is active</li>
            <li><strong>Error logs:</strong> Retained for 30 days for debugging purposes</li>
          </ul>
          <p className="text-foreground leading-relaxed mt-4">
            After the retention period, we securely delete or anonymize your data.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">7. Your Rights</h2>
          <p className="text-foreground leading-relaxed mb-4">
            Under GDPR, you have the following rights regarding your personal data:
          </p>

          <div className="space-y-3">
            <div className="bg-muted p-4 rounded-lg">
              <h3 className="font-medium mb-2">Right to Access</h3>
              <p className="text-sm text-muted-foreground">
                You can request a copy of the personal data we hold about you.
              </p>
            </div>

            <div className="bg-muted p-4 rounded-lg">
              <h3 className="font-medium mb-2">Right to Rectification</h3>
              <p className="text-sm text-muted-foreground">
                You can request correction of inaccurate or incomplete data.
              </p>
            </div>

            <div className="bg-muted p-4 rounded-lg">
              <h3 className="font-medium mb-2">Right to Erasure</h3>
              <p className="text-sm text-muted-foreground">
                You can request deletion of your personal data ("right to be forgotten").
              </p>
            </div>

            <div className="bg-muted p-4 rounded-lg">
              <h3 className="font-medium mb-2">Right to Data Portability</h3>
              <p className="text-sm text-muted-foreground">
                You can request a copy of your data in a structured, machine-readable format.
              </p>
            </div>

            <div className="bg-muted p-4 rounded-lg">
              <h3 className="font-medium mb-2">Right to Object</h3>
              <p className="text-sm text-muted-foreground">
                You can object to processing based on legitimate interests.
              </p>
            </div>

            <div className="bg-muted p-4 rounded-lg">
              <h3 className="font-medium mb-2">Right to Withdraw Consent</h3>
              <p className="text-sm text-muted-foreground">
                Where processing is based on consent, you can withdraw it at any time.
              </p>
            </div>
          </div>

          <p className="text-foreground leading-relaxed mt-6">
            To exercise any of these rights, please contact us at <strong>info@gs1.nl</strong>. 
            We will respond to your request within 30 days.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">8. Data Security</h2>
          <p className="text-foreground leading-relaxed mb-4">
            We implement appropriate technical and organizational measures to protect your 
            personal data:
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground ml-4">
            <li>Encryption of data in transit (HTTPS/TLS) and at rest</li>
            <li>Secure authentication with OAuth 2.0</li>
            <li>Regular security audits and vulnerability assessments</li>
            <li>Access controls and role-based permissions</li>
            <li>Automated backups with 7-day retention</li>
            <li>Rate limiting and DDoS protection</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">9. International Data Transfers</h2>
          <p className="text-foreground leading-relaxed">
            Your data is primarily stored and processed within the European Economic Area (EEA). 
            If we transfer data outside the EEA, we ensure adequate safeguards are in place, 
            such as Standard Contractual Clauses approved by the European Commission.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">10. Cookies and Tracking</h2>
          <p className="text-foreground leading-relaxed mb-4">
            ISA uses minimal cookies necessary for functionality:
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground ml-4">
            <li><strong>Session cookies:</strong> To maintain your login state (essential)</li>
            <li><strong>Analytics cookies:</strong> To understand usage patterns (anonymized)</li>
          </ul>
          <p className="text-foreground leading-relaxed mt-4">
            We do not use advertising or tracking cookies. You can manage cookie preferences 
            in your browser settings.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">11. Children's Privacy</h2>
          <p className="text-foreground leading-relaxed">
            ISA is not intended for individuals under 16 years of age. We do not knowingly 
            collect personal data from children. If you believe we have inadvertently collected 
            data from a child, please contact us immediately.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">12. Changes to This Policy</h2>
          <p className="text-foreground leading-relaxed">
            We may update this privacy policy from time to time to reflect changes in our 
            practices or legal requirements. We will notify you of significant changes by 
            email or through a prominent notice on ISA. The "Last updated" date at the top 
            indicates when the policy was last revised.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">13. Contact Us</h2>
          <p className="text-foreground leading-relaxed mb-4">
            If you have questions about this privacy policy or how we handle your data, 
            please contact us:
          </p>
          <div className="bg-muted p-4 rounded-lg">
            <p className="font-medium">GS1 Netherlands</p>
            <p className="text-muted-foreground">Email: info@gs1.nl</p>
            <p className="text-muted-foreground">Phone: +31 (0)33 450 11 00</p>
            <p className="text-muted-foreground">Address: Stationsplein 9K, 3818 LE Amersfoort, The Netherlands</p>
          </div>
          <p className="text-foreground leading-relaxed mt-4">
            You also have the right to lodge a complaint with the Dutch Data Protection 
            Authority (Autoriteit Persoonsgegevens) if you believe we have not handled your 
            data appropriately.
          </p>
        </section>
      </Card>
    </div>
  );
}
