-- Add regulatory tracking columns to hub_news table
ALTER TABLE `hub_news` 
ADD COLUMN `regulatory_state` ENUM('PROPOSAL','POLITICAL_AGREEMENT','ADOPTED','DELEGATED_ACT_DRAFT','DELEGATED_ACT_ADOPTED','GUIDANCE','ENFORCEMENT_SIGNAL','POSTPONED_OR_SOFTENED') DEFAULT 'ADOPTED',
ADD COLUMN `is_negative_signal` TINYINT DEFAULT 0,
ADD COLUMN `confidence_level` ENUM('CONFIRMED_LAW','DRAFT_PROPOSAL','GUIDANCE_INTERPRETATION','MARKET_PRACTICE') DEFAULT 'GUIDANCE_INTERPRETATION',
ADD COLUMN `negative_signal_keywords` JSON,
ADD COLUMN `regulatory_event_id` INT;
