/**
 * Enhanced Export Utilities with Branding Support
 *
 * Provides PDF and CSV export functionality with customizable branding,
 * logos, headers, and footers for white-label distribution.
 */

import jsPDF from "jspdf";
import { autoTable } from "jspdf-autotable";
import { serverLogger } from "./_core/logger-wiring";


/**
 * Branding configuration for white-label exports
 */
export interface BrandingConfig {
  companyName: string;
  companyLogo?: string; // Base64 encoded image
  logoWidth?: number; // mm
  logoHeight?: number; // mm
  primaryColor?: string; // Hex color
  secondaryColor?: string; // Hex color
  footerText?: string;
  includeWatermark?: boolean;
  watermarkText?: string;
  headerText?: string;
  customCSS?: string;
}

/**
 * Default branding configuration (GS1 branding)
 */
export const DEFAULT_BRANDING: BrandingConfig = {
  companyName: "GS1",
  primaryColor: "#003366",
  secondaryColor: "#0099CC",
  footerText: "Generated by Intelligent Standards Architect (ISA)",
  headerText: "Regulation Compliance Report",
  includeWatermark: false,
};

/**
 * Regulation export data structure
 */
export interface RegulationExportData {
  id: string;
  title: string;
  type: string;
  celexId: string;
  description: string;
  effectiveDate: Date;
  enforcementDate: Date | null;
  status: string;
  applicableSectors: string[];
  applicableGS1Standards: string[];
  implementationPhases: Array<{
    phase: string;
    deadline: string;
    description: string;
  }>;
  relatedRegulations: string[];
  faqItems: Array<{
    question: string;
    answer: string;
  }>;
  checklist: Array<{
    item: string;
    description: string;
    priority: string;
    completed: boolean;
  }>;
}

/**
 * Generate branded PDF from regulation data
 */
export function exportRegulationToPDFBranded(
  data: RegulationExportData,
  branding: BrandingConfig = DEFAULT_BRANDING
): Buffer {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 15;

  // Add header with logo and company name
  if (branding.companyLogo) {
    try {
      doc.addImage(
        branding.companyLogo,
        "PNG",
        15,
        yPosition,
        branding.logoWidth || 30,
        branding.logoHeight || 15
      );
    } catch (error) {
      serverLogger.warn("[Export] Failed to add logo:", error);
    }
  }

  // Company name and header
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(branding.primaryColor || "#000000");
  doc.text(branding.companyName, pageWidth - 15, yPosition + 5, {
    align: "right",
  });

  // Header text
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(branding.headerText || "Regulation Report", 15, yPosition + 12);

  yPosition += 25;

  // Watermark if enabled (simplified without alpha support)
  if (branding.includeWatermark && branding.watermarkText) {
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(60);
    doc.setTextColor(220, 220, 220);
    doc.text(branding.watermarkText, pageWidth / 2, pageHeight / 2, {
      align: "center",
      angle: 45,
    });
    doc.setTextColor(0, 0, 0);
  }

  // Title
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(branding.primaryColor || "#000000");
  const titleLines = doc.splitTextToSize(data.title, pageWidth - 30);
  doc.text(titleLines, 15, yPosition);
  yPosition += titleLines.length * 7 + 5;

  // Regulation metadata
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);

  const metadataTable = [
    ["Type", data.type],
    ["CELEX ID", data.celexId],
    ["Status", data.status],
    ["Effective Date", data.effectiveDate.toLocaleDateString()],
    ...(data.enforcementDate
      ? [["Enforcement Date", data.enforcementDate.toLocaleDateString()]]
      : []),
  ];

  autoTable(doc, {
    startY: yPosition,
    head: [["Property", "Value"]],
    body: metadataTable,
    theme: "grid",
    headStyles: {
      fillColor: branding.primaryColor || "#003366",
      textColor: 255,
      fontStyle: "bold",
    },
    margin: { left: 15, right: 15 },
  });

  yPosition = (doc as any).lastAutoTable.finalY + 10;

  // Description
  if (data.description) {
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(branding.primaryColor || "#000000");
    doc.text("Description", 15, yPosition);
    yPosition += 7;

    doc.setFont("Helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    const descLines = doc.splitTextToSize(data.description, pageWidth - 30);
    doc.text(descLines, 15, yPosition);
    yPosition += descLines.length * 5 + 5;
  }

  // Applicable sectors
  if (data.applicableSectors.length > 0) {
    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = 15;
    }

    doc.setFont("Helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(branding.primaryColor || "#000000");
    doc.text("Applicable Sectors", 15, yPosition);
    yPosition += 7;

    doc.setFont("Helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    data.applicableSectors.forEach(sector => {
      doc.text(`• ${sector}`, 20, yPosition);
      yPosition += 5;
    });
    yPosition += 5;
  }

  // GS1 Standards
  if (data.applicableGS1Standards.length > 0) {
    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = 15;
    }

    doc.setFont("Helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(branding.primaryColor || "#000000");
    doc.text("Applicable GS1 Standards", 15, yPosition);
    yPosition += 7;

    doc.setFont("Helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    data.applicableGS1Standards.forEach(standard => {
      doc.text(`• ${standard}`, 20, yPosition);
      yPosition += 5;
    });
    yPosition += 5;
  }

  // Implementation timeline
  if (data.implementationPhases.length > 0) {
    if (yPosition > pageHeight - 50) {
      doc.addPage();
      yPosition = 15;
    }

    doc.setFont("Helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(branding.primaryColor || "#000000");
    doc.text("Implementation Timeline", 15, yPosition);
    yPosition += 7;

    const timelineTable = data.implementationPhases.map(phase => [
      phase.phase,
      phase.deadline,
      phase.description,
    ]);

    autoTable(doc, {
      startY: yPosition,
      head: [["Phase", "Deadline", "Description"]],
      body: timelineTable,
      theme: "grid",
      headStyles: {
        fillColor: branding.secondaryColor || "#0099CC",
        textColor: 255,
        fontStyle: "bold",
      },
      margin: { left: 15, right: 15 },
    });

    yPosition = (doc as any).lastAutoTable.finalY + 10;
  }

  // Implementation checklist
  if (data.checklist.length > 0) {
    if (yPosition > pageHeight - 50) {
      doc.addPage();
      yPosition = 15;
    }

    doc.setFont("Helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(branding.primaryColor || "#000000");
    doc.text("Implementation Checklist", 15, yPosition);
    yPosition += 7;

    const checklistTable = data.checklist.map(item => [
      item.completed ? "✓" : "○",
      item.item,
      item.priority,
    ]);

    autoTable(doc, {
      startY: yPosition,
      head: [["Status", "Item", "Priority"]],
      body: checklistTable,
      theme: "grid",
      headStyles: {
        fillColor: branding.primaryColor || "#003366",
        textColor: 255,
        fontStyle: "bold",
      },
      margin: { left: 15, right: 15 },
    });

    yPosition = (doc as any).lastAutoTable.finalY + 10;
  }

  // FAQ section
  if (data.faqItems.length > 0) {
    if (yPosition > pageHeight - 50) {
      doc.addPage();
      yPosition = 15;
    }

    doc.setFont("Helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(branding.primaryColor || "#000000");
    doc.text("Frequently Asked Questions", 15, yPosition);
    yPosition += 7;

    data.faqItems.forEach((item, index) => {
      if (yPosition > pageHeight - 30) {
        doc.addPage();
        yPosition = 15;
      }

      doc.setFont("Helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(branding.primaryColor || "#000000");
      doc.text(`Q${index + 1}: ${item.question}`, 15, yPosition);
      yPosition += 6;

      doc.setFont("Helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(50, 50, 50);
      const answerLines = doc.splitTextToSize(item.answer, pageWidth - 30);
      doc.text(answerLines, 20, yPosition);
      yPosition += answerLines.length * 4 + 5;
    });
  }

  // Footer on all pages
  const totalPages = (doc as any).internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);

    // Footer text
    if (branding.footerText) {
      doc.text(branding.footerText, 15, pageHeight - 10);
    }

    // Page number
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 30, pageHeight - 10, {
      align: "right",
    });

    // Divider line
    doc.setDrawColor(200, 200, 200);
    doc.line(15, pageHeight - 12, pageWidth - 15, pageHeight - 12);
  }

  return Buffer.from(doc.output("arraybuffer"));
}

/**
 * Generate filename for export with timestamp
 */
export function generateExportFilename(
  title: string,
  format: "pdf" | "csv"
): string {
  const sanitized = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .substring(0, 50);

  const date = new Date().toISOString().split("T")[0];
  const ext = format === "pdf" ? "pdf" : "csv";

  return `regulation-${sanitized}-${date}.${ext}`;
}

/**
 * Export regulation to CSV with branding header
 */
export function exportRegulationToCSVBranded(
  data: RegulationExportData,
  branding: BrandingConfig = DEFAULT_BRANDING
): string {
  const lines: string[] = [];

  // Header with branding
  lines.push(`"${branding.companyName} - ${branding.headerText}"`);
  lines.push(`"Generated: ${new Date().toISOString()}"`);
  lines.push("");

  // Regulation metadata
  lines.push("REGULATION DETAILS");
  lines.push(`"Title","${escapeCSV(data.title)}"`);
  lines.push(`"Type","${data.type}"`);
  lines.push(`"CELEX ID","${data.celexId}"`);
  lines.push(`"Status","${data.status}"`);
  lines.push(`"Effective Date","${data.effectiveDate.toLocaleDateString()}"`);
  if (data.enforcementDate) {
    lines.push(
      `"Enforcement Date","${data.enforcementDate.toLocaleDateString()}"`
    );
  }
  lines.push("");

  // Description
  if (data.description) {
    lines.push("DESCRIPTION");
    lines.push(`"${escapeCSV(data.description)}"`);
    lines.push("");
  }

  // Sectors
  if (data.applicableSectors.length > 0) {
    lines.push("APPLICABLE SECTORS");
    data.applicableSectors.forEach(sector => {
      lines.push(`"${escapeCSV(sector)}"`);
    });
    lines.push("");
  }

  // GS1 Standards
  if (data.applicableGS1Standards.length > 0) {
    lines.push("APPLICABLE GS1 STANDARDS");
    data.applicableGS1Standards.forEach(standard => {
      lines.push(`"${escapeCSV(standard)}"`);
    });
    lines.push("");
  }

  // Timeline
  if (data.implementationPhases.length > 0) {
    lines.push("IMPLEMENTATION TIMELINE");
    lines.push('"Phase","Deadline","Description"');
    data.implementationPhases.forEach(phase => {
      lines.push(
        `"${escapeCSV(phase.phase)}","${phase.deadline}","${escapeCSV(phase.description)}"`
      );
    });
    lines.push("");
  }

  // Checklist
  if (data.checklist.length > 0) {
    lines.push("IMPLEMENTATION CHECKLIST");
    lines.push('"Status","Item","Priority"');
    data.checklist.forEach(item => {
      lines.push(
        `"${item.completed ? "✓" : "○"}","${escapeCSV(item.item)}","${item.priority}"`
      );
    });
    lines.push("");
  }

  // FAQ
  if (data.faqItems.length > 0) {
    lines.push("FREQUENTLY ASKED QUESTIONS");
    lines.push('"Question","Answer"');
    data.faqItems.forEach(item => {
      lines.push(`"${escapeCSV(item.question)}","${escapeCSV(item.answer)}"`);
    });
    lines.push("");
  }

  // Footer
  lines.push(`"${branding.footerText}"`);

  return lines.join("\n");
}

/**
 * Escape CSV values
 */
function escapeCSV(value: string): string {
  if (!value) return "";
  return value.replace(/"/g, '""');
}
