#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./_agent_fabric_lib.sh
source "$SCRIPT_DIR/_agent_fabric_lib.sh"

echo "PREFLIGHT=render_agent_env"

af_require_cmd jq
af_require_cmd security
af_require_repo_file "$AGENT_FABRIC_SECRET_MAP"

LANE="scm_only"
OUTPUT_PATH=""
PRINT_STDOUT=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --lane)
      LANE="$(af_normalize_lane "${2:-}")"
      shift 2
      ;;
    --output)
      OUTPUT_PATH="${2:-}"
      shift 2
      ;;
    --stdout)
      PRINT_STDOUT=1
      shift
      ;;
    *)
      af_stop "usage_unknown_arg arg=$1"
      ;;
  esac
done

[[ -n "$OUTPUT_PATH" || "$PRINT_STDOUT" -eq 1 ]] || af_stop "missing_output_mode"

af_load_nonsecret_env
entries_json="$(af_secret_entries_json "$LANE")"

tmp_file="$(af_mktemp isa-agent-env .sh)"
chmod 600 "$tmp_file"

{
  echo "#!/usr/bin/env bash"
  echo "# Generated by scripts/dev/render-agent-env.sh"

  if [[ -n "${GOOGLE_CLOUD_PROJECT:-}" ]]; then
    printf 'export GOOGLE_CLOUD_PROJECT=%q\n' "$GOOGLE_CLOUD_PROJECT"
  fi

  if [[ -n "${ISA_AGENT_FABRIC_LABEL:-}" ]]; then
    printf 'export ISA_AGENT_FABRIC_LABEL=%q\n' "$ISA_AGENT_FABRIC_LABEL"
  fi

  printf 'export ISA_AGENT_FABRIC_SECRET_LANE=%q\n' "$LANE"

  while IFS= read -r row; do
    [[ -n "$row" ]] || continue
    env_key="$(jq -r '.env_key' <<<"$row")"
    secret_id="$(jq -r '.secret_id' <<<"$row")"
    backend="$(jq -r '.storage_backend' <<<"$row")"
    service="$(af_keychain_service_from_backend "$backend")" || af_stop "invalid_keychain_backend secret_id=${secret_id}"
    if [[ -n "${!env_key:-}" ]]; then
      value="${!env_key}"
    else
      af_keychain_has "$service" || af_stop "missing_keychain_secret secret_id=${secret_id} service=${service}"
      value="$(af_keychain_get "$service")"
    fi
    printf 'export %s=%q\n' "$env_key" "$value"
  done < <(jq -c '.[]' <<<"$entries_json")
} >"$tmp_file"

if [[ -n "$OUTPUT_PATH" ]]; then
  cp "$tmp_file" "$OUTPUT_PATH"
  chmod 600 "$OUTPUT_PATH"
  echo "READY=agent_env_rendered path=${OUTPUT_PATH} lane=${LANE}"
fi

if [[ "$PRINT_STDOUT" -eq 1 ]]; then
  cat "$tmp_file"
fi

rm -f "$tmp_file"
af_done "render_agent_env_complete lane=${LANE}"
