#!/usr/bin/env python3
"""Phase 4: Automation & CI - Generate validation gates and CI workflows"""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent
OUTPUT_DIR = REPO_ROOT / "docs/planning/refactoring"
GITHUB_DIR = REPO_ROOT / ".github/workflows"

def generate_validation_script():
    """Generate validation gate script"""
    
    script = """#!/bin/bash
# ISA Refactoring Validation Gates
# Auto-generated by phase_4_automation.py

set -e

echo "ISA Refactoring Validation Gates"
echo "================================="

# Gate 1: File Inventory Exists
echo "Gate 1: File Inventory..."
if [ ! -f "docs/planning/refactoring/FILE_INVENTORY.json" ]; then
    echo "❌ FAIL: FILE_INVENTORY.json missing"
    exit 1
fi
echo "✅ PASS"

# Gate 2: All Contracts Exist
echo "Gate 2: Runtime Contracts..."
CONTRACTS=(
    "docs/spec/ASK_ISA/RUNTIME_CONTRACT.md"
    "docs/spec/NEWS_HUB/RUNTIME_CONTRACT.md"
    "docs/spec/KNOWLEDGE_BASE/RUNTIME_CONTRACT.md"
    "docs/spec/CATALOG/RUNTIME_CONTRACT.md"
    "docs/spec/ESRS_MAPPING/RUNTIME_CONTRACT.md"
    "docs/spec/ADVISORY/RUNTIME_CONTRACT.md"
)

for contract in "${CONTRACTS[@]}"; do
    if [ ! -f "$contract" ]; then
        echo "❌ FAIL: $contract missing"
        exit 1
    fi
done
echo "✅ PASS (6/6 contracts)"

# Gate 3: Quality Scorecards
echo "Gate 3: Quality Scorecards..."
if [ ! -f "docs/planning/refactoring/QUALITY_SCORECARDS.json" ]; then
    echo "❌ FAIL: QUALITY_SCORECARDS.json missing"
    exit 1
fi

SCORE=$(jq -r '.overall_score' docs/planning/refactoring/QUALITY_SCORECARDS.json)
if (( $(echo "$SCORE < 60" | bc -l) )); then
    echo "❌ FAIL: Overall score $SCORE < 60"
    exit 1
fi
echo "✅ PASS (score: $SCORE)"

# Gate 4: No Broken Links (basic check)
echo "Gate 4: Link Validation..."
BROKEN=0
for md in $(find docs -name "*.md"); do
    # Check for broken relative links
    grep -oP '\\[.*?\\]\\((?!http).*?\\)' "$md" | while read -r link; do
        path=$(echo "$link" | sed -E 's/.*\\((.*)\\)/\\1/')
        dir=$(dirname "$md")
        if [ ! -f "$dir/$path" ] && [ ! -f "docs/$path" ]; then
            echo "⚠️  Potential broken link in $md: $path"
            BROKEN=$((BROKEN + 1))
        fi
    done
done
echo "✅ PASS (basic check)"

# Gate 5: UNKNOWN Classification
echo "Gate 5: Classification Coverage..."
UNKNOWN=$(jq '[.files[] | select(.capability == "UNKNOWN")] | length' docs/planning/refactoring/FILE_INVENTORY.json)
TOTAL=$(jq '.files | length' docs/planning/refactoring/FILE_INVENTORY.json)
PERCENT=$(echo "scale=1; $UNKNOWN * 100 / $TOTAL" | bc)

if (( $(echo "$PERCENT > 5" | bc -l) )); then
    echo "❌ FAIL: UNKNOWN files $PERCENT% > 5%"
    exit 1
fi
echo "✅ PASS (UNKNOWN: $PERCENT%)"

echo ""
echo "================================="
echo "✅ ALL GATES PASSED"
"""
    
    output_path = REPO_ROOT / "scripts/refactor/validate_gates.sh"
    output_path.write_text(script)
    output_path.chmod(0o755)
    
    return output_path

def generate_ci_workflow():
    """Generate GitHub Actions workflow"""
    
    workflow = """name: ISA Refactoring Validation

on:
  push:
    branches: [ main, isa_web_clean_Q_branch ]
    paths:
      - 'docs/**'
      - 'scripts/refactor/**'
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: Install jq and bc
      run: sudo apt-get update && sudo apt-get install -y jq bc
    
    - name: Run Validation Gates
      run: |
        chmod +x scripts/refactor/validate_gates.sh
        scripts/refactor/validate_gates.sh
    
    - name: Check Quality Score
      run: |
        SCORE=$(jq -r '.overall_score' docs/planning/refactoring/QUALITY_SCORECARDS.json)
        echo "Overall Quality Score: $SCORE/100"
        if (( $(echo "$SCORE < 60" | bc -l) )); then
          echo "::error::Quality score below threshold"
          exit 1
        fi
    
    - name: Generate Report
      if: always()
      run: |
        echo "## Refactoring Validation Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ -f docs/planning/refactoring/QUALITY_SCORECARDS.json ]; then
          echo "### Quality Scores" >> $GITHUB_STEP_SUMMARY
          jq -r '.capabilities | to_entries[] | "- **\\(.key):** \\(.value.grade) (\\(.value.score)/100)"' \
            docs/planning/refactoring/QUALITY_SCORECARDS.json >> $GITHUB_STEP_SUMMARY
        fi
"""
    
    output_path = GITHUB_DIR / "refactoring-validation.yml"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(workflow)
    
    return output_path

def generate_automation_summary():
    """Generate Phase 4 summary"""
    
    print("Phase 4: Automation & CI")
    print("=" * 60)
    
    print("\n1. Generating validation gates...")
    gate_script = generate_validation_script()
    print(f"   Created: {gate_script.relative_to(REPO_ROOT)}")
    
    print("\n2. Generating CI workflow...")
    workflow = generate_ci_workflow()
    print(f"   Created: {workflow.relative_to(REPO_ROOT)}")
    
    print("\n3. Testing validation gates...")
    import subprocess
    result = subprocess.run(
        [str(gate_script)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True
    )
    
    if result.returncode == 0:
        print("   ✅ All gates passed")
    else:
        print(f"   ⚠️  Some gates failed (expected in development)")
        print(f"   Output: {result.stdout}")
    
    # Save summary
    summary = {
        'version': '1.0',
        'generated': '2026-02-12',
        'artifacts': [
            str(gate_script.relative_to(REPO_ROOT)),
            str(workflow.relative_to(REPO_ROOT))
        ],
        'gates': [
            'File Inventory Exists',
            'All Contracts Exist',
            'Quality Score >= 60',
            'Link Validation',
            'UNKNOWN < 5%'
        ],
        'validation_result': result.returncode == 0
    }
    
    summary_path = OUTPUT_DIR / "PHASE_4_SUMMARY.json"
    with open(summary_path, 'w') as f:
        json.dump(summary, f, indent=2)
    
    print(f"\n   Saved: {summary_path.relative_to(REPO_ROOT)}")
    
    print("\n✅ Phase 4 Complete")
    print(f"   - Validation script: {gate_script.name}")
    print(f"   - CI workflow: {workflow.name}")
    print(f"   - Gates defined: {len(summary['gates'])}")

if __name__ == '__main__':
    generate_automation_summary()
