#!/bin/bash
# ISA Refactoring Validation Gates
# Auto-generated by phase_4_automation.py

set -e

echo "ISA Refactoring Validation Gates"
echo "================================="

# Gate 1: File Inventory Exists
echo "Gate 1: File Inventory..."
if [ ! -f "docs/planning/refactoring/FILE_INVENTORY.json" ]; then
    echo "❌ FAIL: FILE_INVENTORY.json missing"
    exit 1
fi
echo "✅ PASS"

# Gate 2: All Contracts Exist
echo "Gate 2: Runtime Contracts..."
CONTRACTS=(
    "docs/spec/ASK_ISA/RUNTIME_CONTRACT.md"
    "docs/spec/NEWS_HUB/RUNTIME_CONTRACT.md"
    "docs/spec/KNOWLEDGE_BASE/RUNTIME_CONTRACT.md"
    "docs/spec/CATALOG/RUNTIME_CONTRACT.md"
    "docs/spec/ESRS_MAPPING/RUNTIME_CONTRACT.md"
    "docs/spec/ADVISORY/RUNTIME_CONTRACT.md"
)

for contract in "${CONTRACTS[@]}"; do
    if [ ! -f "$contract" ]; then
        echo "❌ FAIL: $contract missing"
        exit 1
    fi
done
echo "✅ PASS (6/6 contracts)"

# Gate 3: Quality Scorecards
echo "Gate 3: Quality Scorecards..."
if [ ! -f "docs/planning/refactoring/QUALITY_SCORECARDS.json" ]; then
    echo "❌ FAIL: QUALITY_SCORECARDS.json missing"
    exit 1
fi

SCORE=$(jq -r '.overall_score' docs/planning/refactoring/QUALITY_SCORECARDS.json)
if (( $(echo "$SCORE < 60" | bc -l) )); then
    echo "❌ FAIL: Overall score $SCORE < 60"
    exit 1
fi
echo "✅ PASS (score: $SCORE)"

# Gate 4: No Broken Links (basic check)
echo "Gate 4: Link Validation..."
BROKEN=0
for md in $(find docs -name "*.md"); do
    # Check for broken relative links (basic pattern matching)
    grep -oE '\\[[^]]*\\]\\([^)]*\\)' "$md" | while read -r link; do
        path=$(echo "$link" | sed -E 's/.*\\((.*)\\)/\\1/')
        # Skip absolute URLs
        if [[ "$path" == http://* || "$path" == https://* ]]; then
            continue
        fi
        dir=$(dirname "$md")
        if [ ! -f "$dir/$path" ] && [ ! -f "docs/$path" ]; then
            echo "⚠️  Potential broken link in $md: $path"
            BROKEN=$((BROKEN + 1))
        fi
    done
done
echo "✅ PASS (basic check)"

# Gate 5: UNKNOWN Classification
echo "Gate 5: Classification Coverage..."
UNKNOWN=$(jq '[.files[] | select(.capability == "UNKNOWN")] | length' docs/planning/refactoring/FILE_INVENTORY.json)
TOTAL=$(jq '.files | length' docs/planning/refactoring/FILE_INVENTORY.json)
PERCENT=$(echo "scale=1; $UNKNOWN * 100 / $TOTAL" | bc)

if (( $(echo "$PERCENT > 5" | bc -l) )); then
    echo "❌ FAIL: UNKNOWN files $PERCENT% > 5%"
    exit 1
fi
echo "✅ PASS (UNKNOWN: $PERCENT%)"

# Gate 6: Semantic Validation
echo "Gate 6: Semantic Validation..."
if [ ! -f "scripts/refactor/semantic_validator.py" ]; then
    echo "⚠️  SKIP: semantic_validator.py not found"
else
    if python3 scripts/refactor/semantic_validator.py > /dev/null 2>&1; then
        VALIDITY=$(jq -r '.overall_validity' docs/planning/refactoring/SEMANTIC_VALIDATION.json)
        echo "✅ PASS (validity: $VALIDITY%)"
    else
        echo "❌ FAIL: Semantic validation failed"
        exit 1
    fi
fi

echo ""
echo "================================="
echo "✅ ALL GATES PASSED"
